/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author jaime
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    double v[];
    
    public Principal() {
        initComponents();
        txtLongitud.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cmdSuma = new javax.swing.JButton();
        cmdProductoria = new javax.swing.JButton();
        cmdNumeroMayor = new javax.swing.JButton();
        cmdNumeroMenor = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdLlenarManual = new javax.swing.JButton();
        cmdLlenarAutomaticamente = new javax.swing.JButton();
        cmdBorrarr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setText("EJERCICIO 1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Iniciales"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Longitud:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txtLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitudKeyTyped(evt);
            }
        });
        jPanel1.add(txtLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 190, 110));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Calcular"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdSuma.setText("Suma");
        cmdSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSumaActionPerformed(evt);
            }
        });
        jPanel4.add(cmdSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, -1));

        cmdProductoria.setText("Productoria");
        cmdProductoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProductoriaActionPerformed(evt);
            }
        });
        jPanel4.add(cmdProductoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, -1));

        cmdNumeroMayor.setText("Numero mayor");
        cmdNumeroMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNumeroMayorActionPerformed(evt);
            }
        });
        jPanel4.add(cmdNumeroMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, -1));

        cmdNumeroMenor.setText("Numero menor");
        cmdNumeroMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNumeroMenorActionPerformed(evt);
            }
        });
        jPanel4.add(cmdNumeroMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 190, 230));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Resultado"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 20, 180, 120));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 210, 160));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Opciones"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, -1));

        cmdLlenarManual.setText("Llenar Manual");
        cmdLlenarManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarManualActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenarManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, -1));

        cmdLlenarAutomaticamente.setText("Llenar Automaticamente");
        cmdLlenarAutomaticamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarAutomaticamenteActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenarAutomaticamente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, -1));

        cmdBorrarr.setText("Borrar");
        cmdBorrarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarrActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 210, 180));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBorrarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarrActionPerformed

        txtLongitud.setText("");
        txtResultado.setText("");
        
        txtLongitud.requestFocusInWindow();
        v=null;
    }//GEN-LAST:event_cmdBorrarrActionPerformed

    private void txtLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudKeyTyped

        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          } 
    }//GEN-LAST:event_txtLongitudKeyTyped

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int longitud;
        if(txtLongitud.getText().trim().isEmpty()){
            JOptionPane.showConfirmDialog(this, "Digite la longitud","ERROR",JOptionPane.INFORMATION_MESSAGE);
            txtLongitud.requestFocusInWindow();
        }else if(Integer.parseInt(txtLongitud.getText().trim())==0){
            JOptionPane.showMessageDialog(this,"no se puede digitar cero en la longitud");
            txtLongitud.requestFocusInWindow();
            txtLongitud.selectAll();
        }else{
            longitud=Integer.parseInt(txtLongitud.getText());
            v= new double [longitud]; 
            JOptionPane.showMessageDialog(this, "Vector creado exitosamente");
        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdLlenarManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarManualActionPerformed
        double n;
        for (int i = 0; i < v.length; i++) {
        n=Double.parseDouble(JOptionPane.showInputDialog("Digite el elemento (pos."+i+")"));
        v[i]=n;
        
        }
        JOptionPane.showMessageDialog(this, "Vector llenado correctamente");
    }//GEN-LAST:event_cmdLlenarManualActionPerformed
    
    private void cmdLlenarAutomaticamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarAutomaticamenteActionPerformed
        double n;
        for (int i = 0; i < v.length; i++) {
             n=(int)(Math.random()*50+ 1);
            v[i]=n;            
        }
        JOptionPane.showMessageDialog(this,"Vector llenado automaticamente correcto");
    }//GEN-LAST:event_cmdLlenarAutomaticamenteActionPerformed

    private void cmdSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSumaActionPerformed
        double suma=0,n;
        for (int i = 0; i < v.length; i++) {
            n=v[i];
            suma=suma+v[i];
        }
        txtResultado.append(""+suma);
        
    }//GEN-LAST:event_cmdSumaActionPerformed

    private void cmdProductoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProductoriaActionPerformed
        double n,prod=1;
        for (int i = 0; i < v.length; i++) {
            n = v[i];
            prod=prod*v[i];
        }
        txtResultado.append("\n"+prod); 
    }//GEN-LAST:event_cmdProductoriaActionPerformed

    private void cmdNumeroMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNumeroMayorActionPerformed

     double mayor=v[0];
    for (int i = 0; i <v.length; i++) {
         if(v[i]>mayor)
             mayor=v[i];
            }
    txtResultado.append("\n El numero mayor es "+mayor);
    
    
    }//GEN-LAST:event_cmdNumeroMayorActionPerformed

    private void cmdNumeroMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNumeroMenorActionPerformed
        double menor=v[0];
        for (int i = 0; i < v.length; i++) {
            menor=v[0];
            if(v[i]<menor)
             menor=v[i];  
        }
        txtResultado.append("\n El numero menor es "+menor);
    }//GEN-LAST:event_cmdNumeroMenorActionPerformed
                                                // []
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrarr;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLlenarAutomaticamente;
    private javax.swing.JButton cmdLlenarManual;
    private javax.swing.JButton cmdNumeroMayor;
    private javax.swing.JButton cmdNumeroMenor;
    private javax.swing.JButton cmdProductoria;
    private javax.swing.JButton cmdSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
